[theme]
primaryColor = "#2C3E50"  
backgroundColor = "#F9F9F9" 
secondaryBackgroundColor = "#FFFFFF"  
textColor = "#333333"  
font = "serif"  

[header]
title = "DigitalSEE"
subtitle = "Exploring Historical Data"

[footer]
text = "Powered by DigitalSEE"